### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by microSoftware** [Jamling/hexo-generator-i18n#8]
Hello, I installed the package and modified the _config.yml as instructed in your readme
But I can't modify the language of my post/page in the post editor.

Is there something else I need to do?

Thank you

**Comment by Jamling** [comment]
You can add the 2nd/3rd... language dir under `source` dir, then new the page under the dir. After that, change the site language to 2nd/3rd... language, you'll see the assigned language page.

The demo you can visit my blog https://www.ieclipse.cn
The source of demo you can visit https://github.com/Jamling/hexo-site

**Comment by microSoftware** [comment]
@Jamling I've modified the _config.yml like your and I added the folder in source. But still, when I'm in the post/page edit, I can't set the lang of the article in the post setting. I have only the default fields. See: 
![Screen Shot 2019-03-14 at 14 03 26](https://user-images.githubusercontent.com/3915272/54359025-08ce7c00-4662-11e9-936e-97ef9f83587e.png)

**Comment by Jamling** [comment]
Note: The post content will not translated to another language. 
I am not understand which `when I'm in the post/page edit` means, you can run your site by `$ hexo s`, then open the http://127.0.0.1:4000 to test.

**Comment by microSoftware** [comment]
no worries. I will create another standalone Hexo blog for the other language. It will be easier this way. Thanks for your help.
